// deviation
DEVIATION_FAR_LEFT = "far_left";
DEVIATION_LEFT = "left";
DEVIATION_MIDDLE = "middle";
DEVIATION_RIGHT = "right";
DEVIATION_FAR_RIGHT = "far_right";

// steering
STEERING_HARD_LEFT = "hard_left";
STEERING_LEFT = "left";
STEERING_STRAIGHT = "straight";
STEERING_RIGHT = "right";
STEERING_HARD_RIGHT = "hard_right";

// light status
LIGHT_STATUS_GREEN = "green";
LIGHT_STATUS_LESS_GREEN = "less_green";
LIGHT_STATUS_YELLOW = "yellow";
LIGHT_STATUS_LESS_RED = "less_red";
LIGHT_STATUS_RED = "red";

// light distance
DISTANCE_LIGHT_NEAR = "near";
DISTANCE_LIGHT_MEDIUM = "medium";
DISTANCE_LIGHT_FAR = "far";

// speed
SPEED_STOP = "stop";
SPEED_SLOWER = "slower";
SPEED_SLOW = "slow";
SPEED_MEDIUM = "medium";

// obstacle distance
DISTANCE_OBSTACLE_NEAR = "near";
DISTANCE_OBSTACLE_MEDIUM = "medium";
DISTANCE_OBSTACLE_FAR = "far";

export {
  DEVIATION_FAR_LEFT,
  DEVIATION_LEFT,
  DEVIATION_MIDDLE,
  DEVIATION_RIGHT,
  DEVIATION_FAR_RIGHT,
  STEERING_HARD_LEFT,
  STEERING_LEFT,
  STEERING_STRAIGHT,
  STEERING_RIGHT,
  STEERING_HARD_RIGHT,
  LIGHT_STATUS_GREEN,
  LIGHT_STATUS_LESS_GREEN,
  LIGHT_STATUS_YELLOW,
  LIGHT_STATUS_LESS_RED,
  LIGHT_STATUS_RED,
  DISTANCE_LIGHT_NEAR,
  DISTANCE_LIGHT_MEDIUM,
  DISTANCE_LIGHT_FAR,
  SPEED_STOP,
  SPEED_SLOWER,
  SPEED_SLOW,
  SPEED_MEDIUM,
  DISTANCE_OBSTACLE_NEAR,
  DISTANCE_OBSTACLE_MEDIUM,
  DISTANCE_OBSTACLE_FAR,
};
